/* San Eduardo Dashboard — data + bilingual labels.
   Numbers approximate the real project outputs (see cattle-heifer-selection). */
window.SE_DASH = {
  es: {
    appTitle: "Selección de Vaquillonas",
    subtitle: "Inteligencia Ganadera",
    back: "Inicio",
    tabs: ["Tu Rodeo", "Auditoría de Reglas", "El Modelo", "Datos Faltantes", "La Visión", "Modelo 2027"],
    hero: { eyebrow: "San Eduardo · Panel de Análisis", s: ["vacas", "registros IHM", "años", "consistencia"] },
    rodeo: {
      h: "Qué analizó este proyecto", lead: "Procesamos cada registro del campo — planillas Excel, sesiones de IATF y alarmas de WhatsApp — en un único dataset con cada vaca que perteneció al rodeo.",
      cards: [["Vacas identificadas","2.728","en el registro del campo"],["Registros de IHM","5.265","mediciones de productividad"],["Años de datos","5","2022–2026"],["En el modelo","337","vacas con datos completos"]],
      chart1: "Productividad del rodeo (IHM promedio)", chart1cap: "IHM = peso del ternero a 205d ÷ peso de la madre. Escala 0–1.",
      chart2: "Registros de IHM por año", chart2cap: "Vacas con IHM medido cada año",
      note: "El IHM promedio se ubica entre 0,40 y 0,48 en todos los años — típico de una operación Angus-cruza bien manejada en la pampa.",
    },
    audit: {
      h: "¿Con qué consistencia aplica el campo su propia regla?", lead: "El resultado más directo del análisis — sin modelos. Aplicamos la regla documentada a la última cohorte y la comparamos con lo decidido realmente.",
      cards: [["Vaquillonas evaluadas","312","cohorte 2025"],["Consistencia general","49%","regla vs. decisiones"],["Predicción clara","72%","excluye invernada/venta"]],
      chart: "Concordancia por categoría", chartcap: "Para cada decisión real, ¿con qué frecuencia coincide la regla?",
      bars: [["★★★ Cat. 3","100"],["★★ Cat. 2","61"],["★ Cat. 1","47"],["Venta Madre","38"],["Venta S/G","29"],["Invernada","23"]],
      note: "≈28% de las decisiones quedan fuera de la regla escrita — la 'brecha de conocimiento tácito' que el modelo necesitaría aprender.",
    },
    model: {
      h: "¿Qué puede ver la IA con los datos actuales?", lead: "Entrenamos el modelo para explorar, no para predecir. Los resultados son honestos sobre lo que puede y no puede hacer hoy.",
      cards: [["Precisión honesta","35%","holdout @30%"],["Selección al azar","30%","línea de base"],["Señal sobre azar","1,2×","real pero débil"],["Cohorte verificable","405","predicción 2027"]],
      shapT: "Importancia SHAP — ¿qué predice buenas hijas?", shapCap: "Barra más larga = más influyente en el puntaje del modelo",
      shap: [["IHM promedio de la madre","100"],["Año de nacimiento","79"],["Pelaje colorado","42"],["Padre tipo IATF","34"],["IHM más reciente madre","28"],["Pelaje negro","21"]],
      compT: "Precisión en el top 30% por modelo", compCap: "Solapamiento entre el top 30% del modelo y las productoras reales",
      comp: [["Random Forest","44"],["Gradient Boost","41"],["Ridge","36"],["Lineal","34"],["Árbol","33"],["Azar","30"]],
      note: "Señal real pero débil: 35% en la prueba honesta (holdout temporal) vs. 30% al azar. Confirma que hay algo que aprender — falta el dato correcto para aprenderlo.",
    },
    gaps: {
      h: "Qué datos tiene el campo — y qué falta documentar", lead: "Cinco años de datos valiosos. Este diagnóstico muestra qué está registrado, qué tiene brechas y qué mejoraría el análisis.",
      summary: [["3","Sólidas o completas","green"],["1","Parcial","gold"],["3","Faltantes o críticas","crimson"]],
      cols: ["Variable","Estado","Valor predictivo","Acción"],
      rows: [
        ["Identificadores (IDV)","Completo","—","Ninguna"],
        ["Registros de IHM","Completo","Crítico","Extender a 2018"],
        ["IHM de la madre","Parcial","Alto","Registrar cada año"],
        ["Tipo de padre","Bueno","Medio","Ninguna"],
        ["Peso real al nacer","Faltante","Alto","Registrar por ternero"],
        ["Fecha/motivo de baja","Faltante","Alto","Registrar al salir"],
        ["EPDs del padre","No vinculado","Muy alto","Cruzar con Angus Arg."],
      ],
      statusTone: { "Completo":"ok","Bueno":"ok","Parcial":"warn","Faltante":"alert","No vinculado":"alert" },
    },
    vision: {
      h: "De exploración a herramienta real", lead: "La trayectoria, si se cierra la brecha de datos, es concreta.",
      phases: [["Ahora · Año 1","Auditoría & Documentación",["Entregar el informe","Registrar IHM, peso, bajas","Hablar con 2–3 campos"]],["Año 2","Modelo Multifinca",["3 campos estandarizados","Reconstruir con variables nuevas","Validar en campos externos"]],["Año 3","Plataforma Completa",["Autoservicio web","Vista retrospectiva","Base pampeana creciente"]]],
    },
    m2: {
      h: "Modelo 2 — Cohorte 2027", lead: "El modelo rankea 405 vaquillonas nacidas en 2025. La selección real ocurre en 2027 — la primera predicción genuinamente verificable.",
      cards: [["Vaquillonas","405","nacidas 2025"],["Con IHM de madre","389","96% · cobertura de datos"],["Recomendadas","122","top 30% del modelo"],["Regla → Cat.3","87","cumplen criterios"]],
      tableT: "Ranking — top vaquillonas",
      cols: ["Rank","IDV","Puntaje","Top 30%","Regla","IHM madre"],
      rows: [
        ["1","SE-2511","0.612","Sí","★★★","0.58"],["2","SE-2487","0.591","Sí","★★★","0.55"],["3","SE-2530","0.577","Sí","★★","0.51"],
        ["4","SE-2502","0.566","Sí","★★★","0.54"],["5","SE-2518","0.558","Sí","★★","0.49"],["6","SE-2495","0.541","Sí","★","0.47"],
        ["7","SE-2473","0.533","Sí","★★","0.50"],["8","SE-2509","0.521","Sí","★★★","0.52"],["9","SE-2526","0.514","Sí","★","0.45"],
        ["10","SE-2481","0.508","Sí","★★","0.48"],["11","SE-2533","0.497","—","★","0.43"],["12","SE-2490","0.489","—","Inv.","0.39"],
      ],
      note: "El IHM adulto real de estas vaquillonas estará disponible en 2029. Esa será la validación definitiva.",
    },
  },
  en: {
    appTitle: "Heifer Selection",
    subtitle: "Livestock Analytics",
    back: "Home",
    tabs: ["Your Herd", "Rule Audit", "The Model", "Missing Data", "The Vision", "2027 Model"],
    hero: { eyebrow: "San Eduardo · Analysis Panel", s: ["cows", "IHM records", "years", "consistency"] },
    rodeo: {
      h: "What this project analyzed", lead: "We processed every farm record — Excel sheets, IATF sessions and WhatsApp alarms — into one dataset with every cow that belonged to the herd.",
      cards: [["Cows identified","2,728","in the farm registry"],["IHM records","5,265","productivity measurements"],["Years of data","5","2022–2026"],["In the model","337","cows with complete data"]],
      chart1: "Herd productivity (mean IHM)", chart1cap: "IHM = calf weight at 205d ÷ mother's weight. Scale 0–1.",
      chart2: "IHM records per year", chart2cap: "Cows with IHM measured each year",
      note: "Mean IHM sits between 0.40 and 0.48 across all years — typical of a well-managed crossbred Angus operation on the pampa.",
    },
    audit: {
      h: "How consistently does the farm apply its own rule?", lead: "The most direct result of the analysis — no models. We applied the documented rule to the latest cohort and compared with what was actually decided.",
      cards: [["Heifers evaluated","312","2025 cohort"],["Overall consistency","49%","rule vs. decisions"],["Clear prediction","72%","excludes fattening/sale"]],
      chart: "Agreement by category", chartcap: "For each real decision, how often does the rule match?",
      bars: [["★★★ Tier 3","100"],["★★ Tier 2","61"],["★ Tier 1","47"],["Mother Sale","38"],["Sale no-geneal.","29"],["Fattening","23"]],
      note: "≈28% of decisions fall outside the written rule — the 'tacit knowledge gap' a model would need to learn.",
    },
    model: {
      h: "What can the AI see with today's data?", lead: "We trained the model to explore, not to predict. The results are honest about what it can and cannot do today.",
      cards: [["Honest precision","35%","holdout @30%"],["Random selection","30%","baseline"],["Signal over random","1.2×","real but weak"],["Verifiable cohort","405","2027 prediction"]],
      shapT: "SHAP importance — what predicts good daughters?", shapCap: "Longer bar = more influence on the model score",
      shap: [["Mother's mean IHM","100"],["Birth year","79"],["Red coat","42"],["IATF-type sire","34"],["Mother's latest IHM","28"],["Black coat","21"]],
      compT: "Top-30% precision by model", compCap: "Overlap between the model's top 30% and the real top producers",
      comp: [["Random Forest","44"],["Gradient Boost","41"],["Ridge","36"],["Linear","34"],["Tree","33"],["Random","30"]],
      note: "Real but weak signal: 35% in the honest test (temporal holdout) vs. 30% at random. It confirms there's something to learn — the right data to learn it is what's missing.",
    },
    gaps: {
      h: "What data the farm has — and what's missing", lead: "Five years of valuable data. This diagnostic shows what's recorded, what has gaps, and what would improve the analysis.",
      summary: [["3","Solid or complete","green"],["1","Partial","gold"],["3","Missing or critical","crimson"]],
      cols: ["Variable","Status","Predictive value","Action"],
      rows: [
        ["Identifiers (IDV)","Complete","—","None"],
        ["IHM records","Complete","Critical","Extend to 2018"],
        ["Mother's IHM","Partial","High","Record yearly"],
        ["Sire type","Good","Medium","None"],
        ["Real birth weight","Missing","High","Record per calf"],
        ["Exit date/reason","Missing","High","Record on exit"],
        ["Sire EPDs","Unlinked","Very high","Link to Angus Arg."],
      ],
      statusTone: { "Complete":"ok","Good":"ok","Partial":"warn","Missing":"alert","Unlinked":"alert" },
    },
    vision: {
      h: "From exploration to a real tool", lead: "The trajectory, if the data gap closes, is concrete.",
      phases: [["Now · Year 1","Audit & Documentation",["Deliver the report","Record IHM, weight, exits","Talk to 2–3 farms"]],["Year 2","Multi-Farm Model",["3 standardized farms","Rebuild with new variables","Validate on external farms"]],["Year 3","Full Platform",["Web self-service","Retrospective view","A growing pampa database"]]],
    },
    m2: {
      h: "Model 2 — 2027 Cohort", lead: "The model ranks 405 heifers born in 2025. Real selection happens in 2027 — the first genuinely verifiable prediction.",
      cards: [["Heifers","405","born 2025"],["With mother IHM","389","96% · data coverage"],["Recommended","122","model's top 30%"],["Rule → Tier 3","87","meet criteria"]],
      tableT: "Ranking — top heifers",
      cols: ["Rank","IDV","Score","Top 30%","Rule","Mother IHM"],
      rows: [
        ["1","SE-2511","0.612","Yes","★★★","0.58"],["2","SE-2487","0.591","Yes","★★★","0.55"],["3","SE-2530","0.577","Yes","★★","0.51"],
        ["4","SE-2502","0.566","Yes","★★★","0.54"],["5","SE-2518","0.558","Yes","★★","0.49"],["6","SE-2495","0.541","Yes","★","0.47"],
        ["7","SE-2473","0.533","Yes","★★","0.50"],["8","SE-2509","0.521","Yes","★★★","0.52"],["9","SE-2526","0.514","Yes","★","0.45"],
        ["10","SE-2481","0.508","Yes","★★","0.48"],["11","SE-2533","0.497","—","★","0.43"],["12","SE-2490","0.489","—","Fatt.","0.39"],
      ],
      note: "These heifers' real adult IHM will be available in 2029. That will be the definitive validation.",
    },
  },
};
